# src/texts.py

translations = {
    "en": {
        "sidebar_title": "Data Analysis",
        "sidebar_info": "Dataset: TMDB 10k Most Popular Movies",
        "show_charts": "Show Dataset Charts",
        "chart_title": "Popularity Distribution",
        "tech_explanation": "**Technique:** Content-Based Filtering using Cosine Similarity on text vectors (Genres + Keywords).",
        "app_title": "🎬 Movie Recommender AI",
        "app_subtitle": "Find your next favorite movie using Artificial Intelligence.",
        "tab1": "🔍 Search by Movie",
        "tab2": "🧠 Search by Preferences",
        "tab1_header": "Because you liked...",
        "select_movie": "Choose a movie:",
        "btn_recommend": "Recommend",
        "success_movie": "Movies similar to **{}**:",
        "similarity": "Similarity",
        "tab2_header": "Describe what you want to watch",
        "tab2_sub": "Type genres or plot elements (e.g., *Action, Space, Robots, Love*).",
        "input_placeholder": "Ex: Science Fiction time travel paradox",
        "btn_text_rec": "Find Matches",
        "success_text": "Best matches for: **'{}'**",
        "warning_input": "Please type something to search.",
        "footer": "Developed for the AI Class - BSI",
        "popover": "Read Synopsis",
    },
    "pt": {
        "sidebar_title": "Análise de Dados",
        "sidebar_info": "Dataset: TMDB 10k Filmes Populares",
        "show_charts": "Mostrar Gráficos do Dataset",
        "chart_title": "Distribuição de Popularidade",
        "tech_explanation": "**Técnica:** Filtragem Baseada em Conteúdo usando Similaridade de Cosseno em vetores de texto.",
        "app_title": "🎬 Sistema de Recomendação",
        "app_subtitle": "Encontre seu próximo filme favorito usando Inteligência Artificial.",
        "tab1": "🔍 Busca por Filme",
        "tab2": "🧠 Busca por Preferências",
        "tab1_header": "Porque você gostou de...",
        "select_movie": "Escolha um filme:",
        "btn_recommend": "Recomendar",
        "success_movie": "Filmes similares a **{}**:",
        "similarity": "Semelhança",
        "tab2_header": "Descreva o que você quer ver",
        "tab2_sub": "Digite gêneros ou elementos de enredo (ex: *Ação, Espaço, Robôs*).",
        "input_placeholder": "Ex: Ficção Científica viagem no tempo",
        "btn_text_rec": "Encontrar Filmes",
        "success_text": "Melhores resultados para: **'{}'**",
        "warning_input": "Por favor, digite algo para buscarmos.",
        "footer": "Desenvolvido para a disciplina de Inteligência Artificial - BSI",
        "popover": "Ler Sinopse",
    },
}
